<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="front-end-developer and back-end-developeraspx.aspx.vb" Inherits="Wij_Software_5.front_end_developer_and_back_end_developeraspx" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            font-weight: bold;
        }
        .auto-style2 {
            font-size: medium;
        }
        .auto-style12 {
            font-size: xx-large;
            text-decoration: underline;
        }
        .auto-style13 {
            font-size: large;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                front-end-developer</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <strong style="font-weight: bold;">You:</strong></p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                You will be an experienced Front-End developer, a keen team player &amp; it goes without saying, you must live and breathe Flight Sim (let&#39;s face it, you wouldn&#39;t be looking at this otherwise).</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                You must have a specialisation in Angular (of course other MVC framework experience is great too).</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                You will be working with a small but fast flowing team and must be able to adhere to the latest agile methodologies. You will be passionate about developing the &quot;right way&quot;.</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                This is a great opportunity for the right person to develop their skills using the latest cutting edge software within the Flight Simulation industry with other similarly minded individuals.</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                The working approach is highly collaborative, progressive &amp; employs agile throughout. As a team player, we expect you to share ideas and methodologies to improve workflow and overall company progress.</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                The culture of the company is relaxed, informal yet professional, with a love of all things technology &amp; aviation!</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <strong style="font-weight: bold;">You will need:</strong></p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                visualstudio 2019 or 2007</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <strong><span class="auto-style1">vb.net</span></strong></p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <strong>aps . net</strong></p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                unity c+++</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                GitHub YOU NEED TOfollowing&nbsp; willairwayvirtual</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                gitlabYOU NEED TOfollowing<span class="auto-style13">&nbsp; </span>
            <span class="auto-style12"><strong>&nbsp;<u><span style="line-height:107%;
font-family:&quot;Calibri&quot;,sans-serif;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:
Calibri;mso-fareast-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:&quot;Times New Roman&quot;;mso-bidi-theme-font:minor-bidi;
mso-ansi-language:EN-GB;mso-fareast-language:EN-US;mso-bidi-language:AR-SA" class="auto-style13">Wij </span><span style="line-height:107%;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:Calibri;mso-fareast-theme-font:minor-latin;color:black;
border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm;
mso-ansi-language:EN-GB;mso-fareast-language:EN-US;mso-bidi-language:AR-SA" class="auto-style13">Software </span></u>&nbsp;</strong></span></p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <span style="color: rgba(0, 0, 0, 0.87); font-family: arial, sans-serif-light, sans-serif; font-size: 24px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Zoom Video Communications</span></p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                &nbsp;</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Job Type:<span>&nbsp;volunteers&nbsp; contractor</span></p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Compensation:<span>&nbsp;</span><strong style="font-weight: bold;">Dependant on experience</strong></p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Experience:</p>
            <ul style="margin: 0px 0px 24px; padding: 0px 0px 0px 30px; list-style: disc; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <li>Front-End Development: 3 years (Preferred), 1.5 years (Absolute Minimum)</li>
            </ul>
            <p>
                &nbsp;</p>
            <p>
                back-end-developer</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <strong style="font-weight: bold;">You:</strong></p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                You will be an experienced Back-End developer, a keen team player &amp; it goes without saying, you must live and breathe Flight Sim (let&#39;s face it, you wouldn&#39;t be looking at this otherwise).</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                You must have a specialisation in Laravel (of course other MVC framework experience is great too - Symfony/Zend to name a few).</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                You will be working with a small but fast flowing team and must be able to adhere to the latest agile methodologies. You will be passionate about developing the &quot;right way&quot;.</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                This is a great opportunity for the right person to develop their skills using the latest cutting edge software within the Flight Simulation industry with other similarly minded individuals.</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                The working approach is highly collaborative, progressive &amp; employs agile throughout. As a team player, we expect you to share ideas and methodologies to improve workflow and overall company progress.</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                The culture of the company is relaxed, informal yet professional, with a love of all things technology &amp; aviation!</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <strong style="font-weight: bold;">You will need:</strong></p>
            <ul class="auto-style2" style="margin: 0px 0px 24px; padding: 0px 0px 0px 30px; list-style: disc; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <li>vb. net framework experience such as Angular</li>
                <li>AccessDatabaseEngine</li>
                <li>Docker / Vagrant</li>
                <li>Electron experience</li>
                <li>Security knowledge/awareness</li>
                <li>Knowledge of Web fundamentals like HTM AND asp.net 4.6.1</li>
                <li>Knowledge of good software design principles (SOLID)</li>
                <li>Knowledge &amp; experience using source control (Git/GitHub/gitlab</li>
                <li>Agile Methodologies</li>
                <li>Adaptable team player, keen to learn new technologies</li>
                <li>c++</li>
            </ul>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Job Type:<span>&nbsp;volunteers contractor</span></p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Compensation:<span>&nbsp;</span><strong style="font-weight: bold;">Dependant on experience</strong></p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Experience:</p>
            <ul style="margin: 0px 0px 24px; padding: 0px 0px 0px 30px; list-style: disc; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <li>Back-End Development: 3 years (Preferred), 1.5 years (Absolute Minimum)</li>
            </ul>
            <p>
                &nbsp;</p>
            <p>
                &nbsp;</p>
            <p style="margin: 0px 0px 24px; color: rgb(129, 129, 129); font-family: Whitney, Calibri, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                &nbsp;</p>
        </div>
    </form>
</body>
</html>
